# Generated by Django 4.2.30 on 2026-07-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_vendor_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vendor_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, null=True),
        ),
    ]
