# Generated by Django 4.2.30 on 2026-07-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_vendor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gst_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='product_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
