# Generated by Django 4.2.30 on 2026-07-19 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('vendor', 'Vendor'), ('admin', 'Admin')], db_index=True, default='client', max_length=20),
        ),
    ]
