# Generated by Django 4.2.30 on 2026-07-18 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('header_text', models.TextField(blank=True, null=True)),
                ('footer_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft / Quotation'), ('confirmed', 'Confirmed'), ('picked_up', 'Picked Up'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('settled', 'Settled / Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('actual_return_date', models.DateTimeField(blank=True, null=True)),
                ('fulfillment_type', models.CharField(choices=[('delivery', 'Delivery'), ('store_pickup', 'Store Pickup')], default='store_pickup', max_length=20)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('total_rent_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_deposit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('deposit_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('deposit_refunded', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('late_fee_charged', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RentalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selected_variants', models.JSONField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('rental_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rentals.rentalorder')),
            ],
        ),
        migrations.CreateModel(
            name='RentalInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateTimeField(auto_now_add=True)),
                ('condition_rating', models.CharField(choices=[('good', 'Good Condition'), ('damaged', 'Damaged'), ('needs_repair', 'Needs Repair')], default='good', max_length=20)),
                ('damage_notes', models.TextField(blank=True, null=True)),
                ('missing_accessories', models.TextField(blank=True, null=True)),
                ('repair_initiated', models.BooleanField(default=False)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspected_orders', to=settings.AUTH_USER_MODEL)),
                ('rental_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='rentals.rentalorder')),
            ],
        ),
        migrations.CreateModel(
            name='DepositHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('collect', 'Collection'), ('refund', 'Refund'), ('deduct', 'Deduction')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('rental_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_history', to='rentals.rentalorder')),
            ],
        ),
    ]
