# Generated by Django 4.2.30 on 2026-07-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_rentalorder_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalorder',
            name='actual_pickup',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
