# Generated by Django 4.2.30 on 2026-07-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_rentalorder_actual_pickup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposithistory',
            name='rental_order',
        ),
        migrations.RemoveField(
            model_name='rentalorder',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='rentalorder',
            name='deposit_paid',
        ),
        migrations.RemoveField(
            model_name='rentalorder',
            name='deposit_refunded',
        ),
        migrations.RemoveField(
            model_name='rentalorder',
            name='late_fee_charged',
        ),
        migrations.RemoveField(
            model_name='rentalorder',
            name='total_deposit_amount',
        ),
        migrations.RemoveField(
            model_name='rentalorder',
            name='total_rent_amount',
        ),
        migrations.AddIndex(
            model_name='rentalorder',
            index=models.Index(fields=['status', 'start_date'], name='rentals_ren_status_ca1916_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalorder',
            index=models.Index(fields=['status', 'end_date'], name='rentals_ren_status_9301b3_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalorder',
            index=models.Index(fields=['client', 'status'], name='rentals_ren_client__ffedec_idx'),
        ),
        migrations.DeleteModel(
            name='DepositHistory',
        ),
    ]
