# Generated by Django 4.2.30 on 2026-07-18 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rentals', '0004_remove_deposithistory_rental_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rental_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='rentals.rentalorder')),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['rental_order'], name='rentals_rev_rental__d946c5_idx'), models.Index(fields=['reviewer'], name='rentals_rev_reviewe_b5c763_idx'), models.Index(fields=['reviewee'], name='rentals_rev_reviewe_0f91c1_idx')],
            },
        ),
    ]
