# Generated by Django 4.2.30 on 2026-07-18 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_rentalorder_public_id'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Held', 'Held'), ('Refunded', 'Refunded'), ('Partial Deduction', 'Partial Deduction')], default='Held', max_length=20)),
                ('penalty_deducted', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='security_deposits', to='rentals.rentalorder')),
            ],
        ),
    ]
