# Generated by Django 4.2.30 on 2026-07-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_securitydeposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='settled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['rental_order', 'status'], name='finance_pay_rental__f99340_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_type', 'status', 'created_at'], name='finance_pay_payment_e7da12_idx'),
        ),
        migrations.AddIndex(
            model_name='securitydeposit',
            index=models.Index(fields=['order', 'status'], name='finance_sec_order_i_dc72da_idx'),
        ),
    ]
