# Generated by Django 4.2.30 on 2026-07-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalperiod',
            name='duration_days',
        ),
        migrations.AddField(
            model_name='rentalperiod',
            name='duration',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rentalperiod',
            name='unit',
            field=models.CharField(choices=[('Hours', 'Hours'), ('Days', 'Days'), ('Weeks', 'Weeks'), ('Months', 'Months')], default='Days', max_length=20),
        ),
    ]
