# Generated by Django 4.2.30 on 2026-07-18 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_rentalperiod_duration_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('security_deposit_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage of Rent')], default='fixed', max_length=20)),
                ('security_deposit_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('late_fee_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('late_fee_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grace_period_hours', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='available_qty',
        ),
        migrations.RemoveField(
            model_name='product',
            name='grace_period_hours',
        ),
        migrations.RemoveField(
            model_name='product',
            name='late_fee_rate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='late_fee_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='security_deposit_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='security_deposit_value',
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='inventory_p_categor_607069_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['base_price'], name='inventory_p_base_pr_881ae1_idx'),
        ),
        migrations.AddField(
            model_name='product',
            name='rental_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.rentalpolicy'),
        ),
    ]
