# Generated by Django 4.2.30 on 2026-07-18 16:47

from django.db import migrations, models

def populate_product_codes(apps, schema_editor):
    Product = apps.get_model('inventory', 'Product')
    import re
    
    products = Product.objects.filter(product_code__isnull=True).order_by('id')
    
    # Find highest existing code
    last_product = Product.objects.filter(product_code__regex=r'^PRD-\d+$').order_by('-product_code').first()
    if last_product and last_product.product_code:
        match = re.match(r'^PRD-(\d+)$', last_product.product_code)
        if match:
            next_number = int(match.group(1)) + 1
        else:
            next_number = 1
    else:
        next_number = 1

    for product in products:
        while True:
            code = f"PRD-{next_number:06d}"
            if not Product.objects.filter(product_code=code).exists():
                product.product_code = code
                product.save()
                break
            next_number += 1

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_rentalperiod_duration_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.RunPython(populate_product_codes, reverse_code=migrations.RunPython.noop),
    ]

