# Generated by Django 4.2.30 on 2026-07-18 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_product_code'),
        ('inventory', '0004_rentalpolicy_remove_product_available_qty_and_more'),
    ]

    operations = [
    ]
