# Generated by Django 4.2.30 on 2026-07-18 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_merge_20260718_1927'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricelistitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pricelistitem',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='pricelistitem',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricelistitem',
            name='min_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pricelistitem',
            name='price_type',
            field=models.CharField(choices=[('discount', 'Discount'), ('fixed_price', 'Fixed Price')], default='discount', max_length=20),
        ),
        migrations.AddField(
            model_name='pricelistitem',
            name='selectable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pricelistitem',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricelistitem',
            name='custom_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pricelistitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
    ]
